### ISSUE TITLE
Troubles applying GAN for anomaly detection

### ISSUE THREAD

**Issue by NorManen** [houssamzenati/Efficient-GAN-Anomaly-Detection#1]
Hi Mr Houssam Zenati, 

My name is Norbert and I was amazed with the opportunities of your code. I was trying to use it in a real image dataset to classify inbetween one class of image and a diferent one (one good image and the rest, like "cat" and "no cat"). But I was unable to understand your readme instructions completely. Could you provide and easy example with a real dataset? I've lost a bunch of hours to figure out how to run your code, because I could not completely comprehend it.

If you have little time, also a chat or videochat would be a possibilty, 

Thank you very much and I am here for any question or suggestion, 

**Norbert**.

**Comment by houssamzenati** [comment]
Hi Norbert,

Do send me an email with more details about the versions of TF and Python you use, as well as the specifics details of the problems you are facing.

Thank you for your interest in my research project,
Best,
Houssam

**Comment by danielduplessis** [comment]
I am just getting started with this.  Running into this error.

[13:10:42 ERROR @AnomalyDetection] cannot import name 'do_roc'
Traceback (most recent call last):
  File "C:/Users/t842211/Documents/Python/GAN/Efficient-GAN-Anomaly-Detection-master/main.py", line 40, in run
    mod = importlib.import_module(mod_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\t842211\Documents\Python\GAN\Efficient-GAN-Anomaly-Detection-master\gan\run_mnist.py", line 9, in <module>
    from utils.evaluations import do_prc, do_roc
ImportError: cannot import name 'do_roc'
[13:10:42 ERROR @AnomalyDetection] Uhoh, the script halted with an error.

An inspection of the relevant module shows no method with the name of do_roc.

**Comment by houssamzenati** [comment]
Hi Daniel,

Thanks a lot for reporting this, it should be fixed. If you notice something else, please let me know,
Best

**Comment by lzzlxxlsz** [comment]
hello,have you run the code successfully?
