### ISSUE TITLE
Example parameters

### ISSUE THREAD

**Issue by bradasteiner** [houssamzenati/Efficient-GAN-Anomaly-Detection#2]
Hi, I found your research quite interesting! Could you provide some example sets of parameters that you know to work well with these example datasets?

**Comment by bemoregt** [comment]
Hi, @bradasteiner @houssamzenati 

python3 main.py gan mnist run --nb_epochs=100 --label=9 --w=0.5 --m='cross-e' --d=2 --rd=123

Here is example.

**Comment by tchaton** [comment]
(Net_Trim) thomas@beast:~/virtualens/Efficient-GAN-Anomaly-Detection$ python3 main.py gan mnist run --nb_epochs=100 --label=9 --w=0.5 --m='cross-e' --d=2 --rd=123

 ______   _____       _____       ____   
|_     `.|_   _|     / ___ `.   .'    '. 
  | | `. \ | |      |_/___) |  |  .--.  |
  | |  | | | |   _   .'____.'  | |    | |
 _| |_.' /_| |__/ | / /_____  _|  `--'  |
|______.'|________| |_______|(_)'.____.' 
                                         

[09:35:07 INFO @AnomalyDetection] Running script at gan.run_mnist
/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[09:35:10 INFO @GAN.train.mnist.cross-e.9] Building training graph...
[09:35:10 WARNING @GAN.train.mnist.cross-e.9] The GAN is training with the following parameters:
Batch size:  100
Starting learning rate:  1e-05
EMA Decay:  0.999
Weight:  0.5
Method for discriminator:  cross-e
Degree for L norms:  2
Anomalous label:  9
[09:35:12 INFO @GAN.train.mnist.cross-e.9] Building testing graph...
[09:35:14 WARNING @tensorflow] From /home/thomas/virtualens/Efficient-GAN-Anomaly-Detection/gan/run_mnist.py:170: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[09:35:14 WARNING @tensorflow] From /home/thomas/virtualens/Efficient-GAN-Anomaly-Detection/gan/run_mnist.py:211: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
[09:35:15 INFO @GAN.train.mnist.cross-e.9] Start training...
2018-06-19 09:35:15.309253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:0a:00.0
totalMemory: 11.92GiB freeMemory: 353.06MiB
2018-06-19 09:35:15.543079: E tensorflow/core/common_runtime/direct_session.cc:154] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12799574016
[09:35:15 ERROR @AnomalyDetection] Failed to create session.
Traceback (most recent call last):
  File "main.py", line 41, in run
    mod.run(args.nb_epochs, args.w, args.m, args.d, args.label, args.rd)
  File "/home/thomas/virtualens/Efficient-GAN-Anomaly-Detection/gan/run_mnist.py", line 329, in run
    train_and_test(nb_epochs, weight, method, degree, random_seed, label)
  File "/home/thomas/virtualens/Efficient-GAN-Anomaly-Detection/gan/run_mnist.py", line 214, in train_and_test
    with sv.managed_session() as sess:
  File "/home/thomas/.pyenv/versions/3.5.0/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 1000, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 989, in managed_session
    start_standard_services=start_standard_services)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 726, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 279, in prepare_session
    config=config)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 180, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1569, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 639, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/thomas/.pyenv/versions/Net_Trim/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
[09:35:15 ERROR @AnomalyDetection] Uhoh, the script halted with an error.

**Comment by houssamzenati** [comment]
Hi both and apologies for the late reply,

Thanks a lot for your reply beromegt,

Please refer to the original paper for all the hyperparameters and arguments. https://arxiv.org/abs/1802.06222

However, default arguments should already be there if I am not mistaken.

Do let me know if you need more help for that matter,
Houssam
